language: objective-c

osx_image: xcode8

notifications:
  slack: rxswift:3ykt2Z61f8GkdvhCZTYPduOL
  email: false

script: 
  - xcodebuild -version
  - xcodebuild -showsdks
  - swift --version
  - ./scripts/all-tests.sh
